const styles = {
    page: {
        minHeight: "100vh",
        background: "#fff",
        display: "flex",
        justifyContent: "center",
        padding: "96px 24px 60px",
    },
    container: {
        maxWidth: "480px",
        width: "100%",
    },
    header: {
        textAlign: "center",
        marginBottom: "28px",
    },
    logoIcon: {
        fontSize: "36px",
        marginBottom: "8px",
    },
    title: {
        fontSize: "24px",
        fontWeight: "700",
        color: "#111",
        margin: "0 0 6px",
    },
    subtitle: {
        fontSize: "14px",
        color: "#888",
        margin: 0,
        lineHeight: 1.5,
    },
    tabs: {
        display: "flex",
        gap: "8px",
        marginBottom: "20px",
    },
    tab: {
        flex: 1,
        padding: "11px",
        border: "1px solid #e5e7eb",
        borderRadius: "8px",
        background: "#fff",
        color: "#888",
        fontSize: "14px",
        fontWeight: "500",
        cursor: "pointer",
        transition: "all 0.15s",
    },
    tabActive: {
        background: "#16a34a",
        borderColor: "#16a34a",
        color: "#fff",
    },
    uploadArea: { marginBottom: "20px" },
    uploadLabel: { cursor: "pointer", display: "block" },
    uploadBox: {
        border: "2px dashed #ddd",
        borderRadius: "12px",
        padding: "44px 20px",
        textAlign: "center",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "8px",
        background: "#fafafa",
    },
    uploadIcon: { fontSize: "36px", color: "#bbb" },
    uploadText: { color: "#444", fontSize: "14px", fontWeight: "500" },
    uploadHint: { color: "#aaa", fontSize: "12px" },
    cameraArea: { marginBottom: "20px", textAlign: "center" },
    video: { width: "100%", borderRadius: "12px", border: "1px solid #e5e7eb" },
    captureBtn: {
        width: "60px", height: "60px", borderRadius: "50%",
        border: "3px solid #16a34a", background: "transparent",
        cursor: "pointer", marginTop: "14px",
        display: "inline-flex", alignItems: "center", justifyContent: "center", padding: 0,
    },
    captureBtnInner: {
        width: "44px", height: "44px", borderRadius: "50%",
        backgroundColor: "#dc2626",
    },
    cameraPlaceholder: {
        border: "2px dashed #ddd", borderRadius: "12px",
        padding: "60px 20px", color: "#aaa", textAlign: "center", background: "#fafafa",
    },
    previewContainer: { textAlign: "center", marginBottom: "20px" },
    previewLabel: { color: "#888", fontSize: "13px", marginBottom: "8px" },
    previewImg: {
        width: "100%", maxHeight: "300px", objectFit: "cover",
        borderRadius: "12px", border: "1px solid #e5e7eb",
    },
    actions: { textAlign: "center", marginBottom: "20px" },
    detectBtn: {
        width: "100%", padding: "14px", border: "none", borderRadius: "8px",
        background: "#16a34a", color: "#fff", fontSize: "15px",
        fontWeight: "600", cursor: "pointer",
    },
    detectBtnDisabled: { opacity: 0.5, cursor: "not-allowed" },
    resultContainer: {
        background: "#fff", borderRadius: "16px",
        border: "1px solid #eee", padding: "24px", marginTop: "8px",
    },
    resultHeader: { textAlign: "center", marginBottom: "20px" },
    resultTitle: { color: "#111", fontSize: "18px", margin: 0, fontWeight: "600" },
    resultCards: { display: "flex", gap: "10px", marginBottom: "20px" },
    resultCard: {
        flex: 1, background: "#fafafa", borderRadius: "10px",
        padding: "16px", display: "flex", flexDirection: "column",
        alignItems: "center", gap: "4px", border: "1px solid #f0f0f0",
    },
    cardIcon: { fontSize: "20px", marginBottom: "4px" },
    cardLabel: {
        color: "#888", fontSize: "11px", textTransform: "uppercase",
        letterSpacing: "0.5px", fontWeight: "600",
    },
    cardValue: { color: "#111", fontSize: "15px", fontWeight: "600", textAlign: "center" },
    progressBar: {
        width: "100%", height: "5px", background: "#eee",
        borderRadius: "3px", marginTop: "6px", overflow: "hidden",
    },
    progressFill: { height: "100%", borderRadius: "3px", transition: "width 0.5s" },
    penangananSection: { marginBottom: "20px" },
    penangananTitle: { color: "#166534", fontSize: "15px", fontWeight: "600", marginBottom: "12px" },
    penangananCard: {
        display: "flex", gap: "12px", alignItems: "flex-start",
        background: "#f0fdf4", border: "1px solid #dcfce7",
        borderRadius: "10px", padding: "14px", marginBottom: "8px",
    },
    penangananNumber: {
        minWidth: "28px", height: "28px", borderRadius: "50%",
        background: "#16a34a", color: "#fff",
        display: "flex", alignItems: "center", justifyContent: "center",
        fontWeight: "600", fontSize: "13px", flexShrink: 0,
    },
    penangananContent: { flex: 1 },
    penangananJudul: { color: "#111", fontWeight: "600", fontSize: "14px", margin: "0 0 3px" },
    penangananDesc: { color: "#666", fontSize: "13px", margin: 0, lineHeight: 1.5 },
    resetBtn: {
        width: "100%", padding: "12px", border: "1px solid #e5e7eb",
        borderRadius: "8px", background: "#fff", color: "#555",
        fontSize: "14px", fontWeight: "500", cursor: "pointer",
    },
    footer: { textAlign: "center", color: "#bbb", fontSize: "12px", marginTop: "36px" },
};

export default styles;
